source("./general_test.R")
source("~/GitHub/inhibitiontasks/helper_functions/helper_functions.R")
source("./test_publication.R")
source("./test_study.R")
source("./test_data.R")
source("~/GitHub/inhibitiontasks/helper_functions/column_names_db.R")
source("~/GitHub/inhibitiontasks/helper_functions/column_names_test.R")